### ISSUE TITLE
Compile dependency com.opengamma.external.json:json is not available in maven central repository

### ISSUE THREAD

**Issue by onecupofspam** [jimmoores/quandl4j#11]
Hello. I've tried to use your library in my application with Gradle build system (with maven central repository) but I got this error during compilation:

Could not resolve all dependencies for configuration ':app-core:compile'.
> Could not resolve com.opengamma.external.json:json:1.0.0.v20101106.
  Required by:
      com.haulmont.guardian:app-core:0.1-SNAPSHOT > com.jimmoores:quandl:1.2.0
   > java.lang.NullPointerException (no error message)

I've checked, and, indeed, there isn't no library with groupId "com.opengamma.external.json" available in maven central: http://search.maven.org/#search%7Cga%7C1%7Ccom.opengamma.external.json

Also: http://mvnrepository.com/artifact/com.opengamma.external.json/json/1.0.0.v20101106

**Comment by jimmoores** [comment]
Hi,

You need to include the opengamma maven repository.  From the POM:

  <repositories>
    <repository>
      <id>og-public</id>
      <name>OG Public</name>
      <url>http://maven.opengamma.com/nexus/content/groups/public</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>og-public</id>
      <name>OG Public</name>
      <url>http://maven.opengamma.com/nexus/content/groups/public</url>
    </pluginRepository>
  </pluginRepositories>

I'm going to try and get rid of them eventually and switch to exclusively using libraries in Maven central, but if you add these you should be able to build fine.

**Comment by MartinanderssonDotcom** [comment]
What Jim said, with some Gradle flavor:

```
repositories {
    maven {
        // Quandl4j has a dependency not in Maven: 'com.opengamma.external.json:json:1.0.0.v20101106'
        // Source of this URL: https://github.com/jimmoores/quandl4j/blob/master/pom.xml
        url "http://maven.opengamma.com/nexus/content/groups/public"
    }
}
```

For completeness, here's all the magic text we need in our `build.gradle` file:

```
repositories {
   // Or use mavenCentral(). I prefer new and cool shit + HTTPS, hence jcenter():
    jcenter()
}

repositories {
    maven {
        // Quandl4j has a dependency not in Maven: 'com.opengamma.external.json:json:1.0.0.v20101106'
        // Source of this URL: https://github.com/jimmoores/quandl4j/blob/master/pom.xml
        url "http://maven.opengamma.com/nexus/content/groups/public"
    }
}

dependencies {
    compile 'com.jimmoores:quandl:1.3.0'
}
```

**Comment by jimmoores** [comment]
I hope you don't mind but I've added this info to the README, many thanks for sharing!

**Comment by misto** [comment]
I'm now getting a "Bad Gateway" from maven.opengamma.com. Any ideas if it's gone for good or just a temporary problem?

**Comment by misto** [comment]
I've just tried to replace their json library with the original one (http://mvnrepository.com/artifact/org.json/json) and it builds and tests fine.. any specific reason why you used theirs?

**Comment by jimmoores** [comment]
Hi Mirko,

Sorry you've been having trouble.  I think OpenGamma's artifactory repo is
back up now (seems to be when I go there).  I used the opengamma one for
solid licensing reasons: when I was CTO at OpenGamma a license review
discovered there was a legally completely ambiguous clause in the org.json
license "The Software shall be used for Good, not Evil." that in effect
renders that project useless by anyone who cares about a proper license.
The OpenGamma version is a drop in compatible replacement based on google
code - at the time there was nothing else equivalent, but I'm happy to be
proved wrong.

Cheers,

Jim

**Comment by misto** [comment]
I didn't realize they had this in their license, thanks for making me aware! And yes, it's up again. Thanks!
