### ISSUE TITLE
Can i use this with my android project, please help

### ISSUE THREAD

**Issue by yadavji83** [jimmoores/quandl4j#21]
I am trying to use it with my android project and its not working. I added the dependencies like this:

```
repositories {
    // Or use mavenCentral(). I prefer new and cool shit + HTTPS, hence jcenter():
    jcenter()
}

repositories {
    maven {
        // Quandl4j has a dependency not in Maven: 'com.opengamma.external.json:json:1.0.0.v20101106'
        // Source of this URL: https://github.com/jimmoores/quandl4j/blob/master/pom.xml
        url "http://maven.opengamma.com/nexus/content/groups/public"
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':payUMoneysdk')
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
    testCompile 'junit:junit:4.12'
    compile 'com.jimmoores:quandl:1.3.0'
}
```

It gives this error while building:
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class

**Comment by jimmoores** [comment]
You need to add the OpenGamma maven repository to your list of
repositories. It's at maven.opengamma.com. This is because I use their JSON
library in preference to the org.json one because the org.json one has a
stupid license (do no evil or something). I'm not super familiar with
Gradle, but someone else documented how to use Quandl4J with Gradle in the
tutorial.
Hope that helps.
Jim

**Comment by yadavji83** [comment]
yes i did that already if you see the code in my question, i added

```
repositories {
    maven {
        // Quandl4j has a dependency not in Maven: 'com.opengamma.external.json:json:1.0.0.v20101106'
        // Source of this URL: https://github.com/jimmoores/quandl4j/blob/master/pom.xml
        url "http://maven.opengamma.com/nexus/content/groups/public"
    }
}
```

But the problem is i can't use your java library in my android studio. There is no tutorial on how to do that. I tried to import it as a module, but the there are so many errors i face after it.
First error is:
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class

Second is in file QuandlSession.java at this line:
result.append(JSON_COLUMN_NAMES_FIELD, DATE_COLUMN);
error cannot find symbol method append(string,string)

There are many errors i face after adding your library in android studio as a module, maybe its not compatible with android studio or i am doing something terribly wrong. Please help me with android integration if you can.

**Comment by jimmoores** [comment]
I'm not familiar with android studio at all. I'm happy to try and help but
I'm not able to try until tomorrow at the earliest. Are you using ProGuard?
Have you tried this:

http://stackoverflow.com/questions/35796144/progaurd-issue-warningignoring-innerclasses-attribute-for-an-anonymous-inner-c

Jim

**Comment by jimmoores** [comment]
Is this issue still open?

**Comment by yadavji83** [comment]
Yes i never found any solution so i made it using API endpoints directly, with out the library. Also the stackoverflow link, i followed those instructions but no luck. You can close it if you want, thanks for the help

**Comment by jimmoores** [comment]
Thanks for replying.
