### ISSUE TITLE
Why does dataset retrieval use api/v1?

### ISSUE THREAD

**Issue by weaselmetal** [jimmoores/quandl4j#24]
Hey Jim,

I saw that `session.getDataSet()` will query `api/v1`, same for  `getMetaData()`.
`session.search()` will use `api/v3`. Why do the former use `v1`?
Any plans to support `v3` for all requests?

Thanks,
Stefan

**Comment by jimmoores** [comment]
To be honest, I just haven't gotten around to transitioning everything to
the v3 API yet (no idea what happened to v2, presume it was internal).
Happy to take a look at it and see if I can get it updated within the next
day or so.

**Comment by weaselmetal** [comment]
Nice! Thanks Jim! Feel free to close this question any time you consider right.

**Comment by jimmoores** [comment]
Clearly I haven't been able to get to it as quickly as I hoped, I'll try and schedule and time to work on it soon. Do you have any specific time constraints or was it a more general query?

**Comment by weaselmetal** [comment]
It was a general inquiry. api v3 doesn't add anything I'd desperately need as of now. I was more puzzled by the fact that different api version are being used.On Jan 25, 2017 09:32, Jim Moores <notifications@github.com> wrote:Clearly I haven't been able to get to it as quickly as I hoped, I'll try and schedule and time to work on it soon. Do you have any specific time constraints or was it a more general query?

**Comment by benmccann** [comment]
This is fixed now in master

**Comment by jimmoores** [comment]
Thanks to Ben McCann for fixing this.
