### ISSUE TITLE
RESTEASY004655 error

### ISSUE THREAD

**Issue by Olivier-92** [jimmoores/quandl4j#25]
Hello,

First, thank you for this very useful library.

I tested Quandl4j within a java EE application and got the error attached when several clients were requesting data:

[log-RESTEASY004655.txt](https://github.com/jimmoores/quandl4j/files/818485/log-RESTEASY004655.txt)

The error can be fixed closing the response object in DefaultRESTDataProvider#getTabularResponse once it is used.

My environment:
JDK 1.8.0 update 102
Application server : Widlfly 10.1.0.Final
OS : Windows 7
Quandl4j : 1.4.0

Thanks and regards,
Olivier

**Comment by jimmoores** [comment]
Hi Olivier,

Thank you so much for taking the time to let me know about your problem, and doubly so for providing a solution!  I'll be integrating your suggested fix tomorrow.  If you don't have any objections, I'll also add you to the list of contributors - I believe in acknowledging all help in the project.  I'll then follow up with a new release in the coming days.

Best Regards,

Jim

**Comment by Olivier-92** [comment]
Hi Jim,

Thanks for the quick reply and for the release. I'll be glad to be added to the list of contributors, thanks!

Best regards,
Olivier

**Comment by Olivier-92** [comment]
Hi Jim,
You must be extremely busy but would it be possible to get a v1.4.1 with this fix ?
Best regards,
Olivier

**Comment by jimmoores** [comment]
I shall get it out today. Apologies for the delay. I'll let you know when
it's done.

**Comment by jimmoores** [comment]
I've updated the docs, poms, etc and deployed the release to maven central.  It does take a little while to show up in the search (I'll double check a bit later but it's not showing up yet).

**Comment by Olivier-92** [comment]
Thanks you very much, I retrieved the v1.4.1, integrated it and can confirm that I don't encounter this issue anymore. I close this ticket.
BR,
Olivier
