### ISSUE TITLE
[2.0.0] Maven pom not downloading core and tablesaw

### ISSUE THREAD

**Issue by kenfehling** [jimmoores/quandl4j#34]
When I try to install I get 

```
_remote.repositories
quandl-2.0.0.pom.sha1
quandl-2.0.0.pom
```

in `~/.m2/repository/com/jimmoores/quandl/2.0.0` but nothing else under `~/.m2/repository/com/jimmoores/`

Maven 3.5
MacOS 10.12.6

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by jimmoores** [comment]
I'll investigate on a clean machine and get back to you.

**Comment by jimmoores** [comment]
Ok, I see.  My documentation isn't correct.  You need to add dependencies for quandl-core and quandl-tablesaw separately. 

```xml
<dependencies>
  <dependency>
    <groupId>com.jimmoores</groupId>
    <artifactId>quandl-core</artifactId>
    <version>2.0.0</version>
  </dependency>
  <dependency>
    <groupId>com.jimmoores</groupId>
    <artifactId>quandl-tablesaw</artifactId>
    <version>2.0.0</version>
  </dependency>
</dependencies>
```

I'll update the documentation and see if i can get the parent pom working.

**Comment by kenfehling** [comment]
Ahh ok, no problem. Would something like this work? https://github.com/jimmoores/quandl4j/pull/35
