### ISSUE TITLE
java 9 jigsaw compile failure

### ISSUE THREAD

**Issue by sharpTrick** [jimmoores/quandl4j#40]
When attempting to modularize my quandl library which depends on this one I ran into the error

'Invalid module name: '20090211' is not a Java identifier'

I was able to modify the manifest in the problem library to fix this issue.

Details can be found at:
https://github.com/FasterXML/jackson-datatype-json-org/issues/12

My fix is more or less just a hack. Unless I am an idiot (which i haven't ruled out) I believe the development of the json dependency is dead. I don't know where to go to propose a patch. Therefore I don't know how to come up with a long term solution other than changing dependencies, which seems expensive.

I realize that this is not specifically a quandle4j issue as much as an issue of one of its dependencies, however information is power.

Edit: it would appear that FasterXML may solve this issue them selves, TBD

**Comment by jimmoores** [comment]
I'm not really sure how to handle this until they do a release with the fix...  I do realise the json dependency is probably dead, when I looked at options, I didn't really find anything suitable as a replacement.  I'll need to keep supporting it for backwards compatibility anyway.

Any thoughts?

**Comment by benmccann** [comment]
Fix pushed here https://github.com/jimmoores/quandl4j/commit/4917549d3ce61ac95a4889a99d61614a0150e2c1. Let us know if it solves the issue or not

**Comment by jimmoores** [comment]
Don't think the fix is released yet, should be in 2.9.4 when it appears.

**Comment by benmccann** [comment]
Oh yeah, you're right

**Comment by jimmoores** [comment]
It's been released so should fix issue, I've pushed a fix.
