### ISSUE TITLE
java 9 java.activation

### ISSUE THREAD

**Issue by sharpTrick** [jimmoores/quandl4j#41]
Similar to this issue:

https://github.com/spotify/dockerfile-maven/issues/90

javax.activation is no longer available by default. Long term solution is to add 'javax.activation:activation:1.1.1' as a dependency.

**Comment by jimmoores** [comment]
Added dep to master, won't release until other issues are dealt with.

**Comment by benmccann** [comment]
@sharpTrick can you try the latest release 2.1.0?
