### ISSUE TITLE
Drop Java 7 support

### ISSUE THREAD

**Issue by benmccann** [jimmoores/quandl4j#47]
@jimmoores what do you think about dropping Java 7 support? Is there a reason we still have it or a timeline on when you think we might be able to drop it?

The tablesaw project requires Java 8 support, so I removed Java 7 support for the moment. One option would be to add Java 7 support back to core and make only the tablesaw sub-project require Java, but this would make the build more complicated. Or I can finish removing Java 7 support and remove the ThreeTen backport dependency, which would be nice as it would reduce the number of dependencies that we have.

**Comment by benmccann** [comment]
@jimmoores any thoughts about this?

**Comment by jimmoores** [comment]
Sorry for the radio silence. I'm not wild about it, but I guess having the threeten backport hanging around is pretty irritating for modern users. In summary, go for it if you want to take it on.

**Comment by benmccann** [comment]
Ok, I already had a PR pending with the change, so in that case I guess I'll go ahead and merge it
