### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by benmccann** [jimmoores/quandl4j#51]
@jimmoores there's been lots of improvements since the last release. Would it be possible to release `2.1.0`?

**Comment by benmccann** [comment]
@jimmoores would it be possible to release a new version?

**Comment by benmccann** [comment]
@jimmoores would you be able to cut a new release? Or if you don't mind giving me permission, I'm happy to do it

**Comment by jimmoores** [comment]
Yes, of course.  I'll give it a go today.

**Comment by jimmoores** [comment]
Sorry, I didn't see your previous requests.

**Comment by jimmoores** [comment]
Done.

**Comment by benmccann** [comment]
Awesome! Thank you so much!!
