### ISSUE TITLE
HTTP Error 301 - Moved Permanently (RESTEasy incompatibility)

### ISSUE THREAD

**Issue by spawzing** [jimmoores/quandl4j#9]
I am working with quandl4J on Wildfly 8.2.0.final, which implements jax-rs with RESTEasy. When I  perform a dataset request, I get
```java
com.jimmoores.quandl.util.QuandlRuntimeException: Response code to https://quandl.com/api/v1/datasets/ODA/PBARL_USD.csv?auth_token=sxfx7C8dRr2Mi9_Kj2UH&rows=1 was Moved Permanently
```
which stands for HTTP 301 error.

It a static environment, it uses Jersey implementation and everything works fine.

[This](https://issues.apache.org/jira/browse/CXF-6475) link says the problem is related to QuandlSession's API_BASE_URL, that misses **www**.

```java
private static final UriBuilder API_BASE_URL = UriBuilder.fromPath("https://quandl.com/api/v1");
```

Maybe Jersey automatically treats 301 and redirects to the new address.

I strongly advise to add **www** to base url.

**Comment by jimmoores** [comment]
Okay so it's apparently an issue with RESTEasy as well then... I'm working
on a new release but got blindsided by some failing tests for legacy
functionality. I'll try and push a new release out today or tomorrow. If
you want a quick fix, I'd suggest building/installing yourself (with
-DskipTests=true) from the master branch after changing the prefix in
QuandlSession.java.
Cheers,
Jim

I am working with quandl4J on Wildfly 8.2.0.final, which implements jax-rs
with RESTEasy. When I perform a dataset request, I get

com.jimmoores.quandl.util.QuandlRuntimeException: Response code to
https://quandl.com/api/v1/datasets/ODA/PBARL_USD.csv?auth_token=sxfx7C8dRr2Mi9_Kj2UH&rows=1
was Moved Permanently

which stands for HTTP 301 error.

It a static environment, it uses Jersey implementation and everything works
fine.

This <https://issues.apache.org/jira/browse/CXF-6475> link says the problem
is related to QuandlSession's API_BASE_URL, that misses *www*.

private static final UriBuilder API_BASE_URL =
UriBuilder.fromPath("https://quandl.com/api/v1");

Maybe Jersey automatically treats 301 and redirects to the new address.

—
Reply to this email directly or view it on GitHub
<https://github.com/jimmoores/quandl4j/issues/9>.

**Comment by jimmoores** [comment]
I've now released 1.2.0 to maven central which should address the issue.  Would you mind if I added a note in the contributors list that you helped identify the bug?

**Comment by spawzing** [comment]
I appreciate you adding it. 
I am going to test the new version an will post here the results.

**Comment by spawzing** [comment]
It seems ok now. Tested quandl4j 1.2.0 on Wildfly 8.2.0 default RESTEasy impl and it works fine.
Thanks for the quick response and fix.

**Comment by djejaquino** [comment]
Could you please update the note to my new profile username?
